### PR TITLE
Conditionally add polyfill

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by josephfrazier** [comment]
Thanks @jamiebuilds, I've published `v0.0.2` with this fix!

It looks like the Travis build with Node v4 failed, but only due to timeout issues. I tried it locally and it worked fine. I might just increase the timeout to work around this.

**Comment by lukebatchelor** [comment]
Cheers for the super quick turn around time!

**Comment by josephfrazier** [comment]
Sure thing! Out of curiosity, where are y'all using this?

**Comment by lukebatchelor** [comment]
https://bitbucket.org/atlassian/atlaskit-mk-2/

It's just been removed atm due to a bug in babel though :(
(https://github.com/babel/babel/issues/7457)

Will be adding it back once this is fixed though (we're just using a ponyfill in the meantime)

**Comment by josephfrazier** [comment]
Good to know, thanks

**Pull request merged**
